title: LDS Meetinghouses
description: A Proxy for Growth in the LDS Church
theme: jekyll-theme-cayman
github:
  is_project_page: false
output: 
  html_document:
    includes:
       in_header: GA_Script.html
